"""
Hybrid multi-UAV planner:
    A* global planning + Dynamic APF local conflict handling.

How it works
------------
1. A* generates a static global reference path for each UAV.
2. At every logical step, each UAV communicates with nearby UAVs.
3. The UAV selects a short look-ahead waypoint on its A* global path.
4. Dynamic APF plans the rolling-horizon local path toward that waypoint while
   considering static obstacles and neighboring UAV repulsion.
5. The old conflict-detection/yielding layer is kept as a safety backup.

Required files in the same folder:
    a_star.py
    apf_dynamic.py
    map_generator.py
"""

import math
from collections import deque

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

from a_star import astar
from apf_dynamic import apf
from map_generator import generate_test_map


# ==========================================
# Static map and UAV parameters
# ==========================================
class StaticMap:
    def __init__(self, width, height, circles=None, rectangles=None, inflation_radius=0.0):
        self.width = width
        self.height = height
        self.circles = circles if circles else []
        self.rectangles = rectangles if rectangles else []
        self.inflation_radius = inflation_radius  # safe radius around static obstacles
        self.grid_map = self._generate_grid()

    def _generate_grid(self):
        grid = [[0 for _ in range(self.width)] for _ in range(self.height)]
        for y in range(self.height):
            for x in range(self.width):
                # Circle obstacles
                for obs_x, obs_y, obs_r in self.circles:
                    if math.hypot(x - obs_x, y - obs_y) <= (obs_r + self.inflation_radius):
                        grid[y][x] = 1
                        break

                # Rectangle obstacles
                if grid[y][x] == 0:
                    for rx, ry, rw, rh in self.rectangles:
                        if (rx - self.inflation_radius) <= x <= (rx + rw + self.inflation_radius) and \
                           (ry - self.inflation_radius) <= y <= (ry + rh + self.inflation_radius):
                            grid[y][x] = 1
                            break
        return grid

    def is_free_grid(self, x, y):
        return 0 <= x < self.width and 0 <= y < self.height and self.grid_map[y][x] == 0


class UAV:
    def __init__(
        self,
        uav_id,
        start,
        goal,
        safe_radius,
        comm_range,
        horizon,
        global_lookahead=8,
        global_replan_interval=35,
    ):
        self.id = uav_id
        self.pos = np.array(start, dtype=float)
        self.goal = np.array(goal, dtype=float)
        self.safe_radius = safe_radius
        self.comm_range = comm_range
        self.horizon = horizon  # rolling local planning window
        self.max_speed = 1.0

        # Local APF output: future H steps.
        self.current_path = []
        self.velocity = np.array([0.0, 0.0])
        self.is_reached = False

        # A* global path state.
        self.global_path = []          # list[(x, y)] generated by A*
        self.global_path_index = 0
        self.global_lookahead = global_lookahead
        self.global_replan_interval = global_replan_interval
        self.last_global_replan = -10**9
        self.local_target = self.goal.copy()

        # Deadlock/yielding state.
        self.wait_steps = 0
        self.is_yielding = False
        self.yield_timer = 0

        # Trajectory memory.
        self.history = []              # recent positions for APF memory
        self.trajectory = [self.pos.copy()]  # full trajectory for visualization

    def get_distance(self, other_pos):
        return np.linalg.norm(self.pos - other_pos)

    def _clip_to_grid(self, point, static_map):
        """Convert a continuous point to a valid grid cell."""
        grid = (int(round(point[0])), int(round(point[1])))
        return (
            max(0, min(static_map.width - 1, grid[0])),
            max(0, min(static_map.height - 1, grid[1])),
        )

    def _nearest_free_grid(self, grid, static_map):
        """Move a grid cell to the nearest free cell if it falls inside an obstacle."""
        sx, sy = grid
        if static_map.is_free_grid(sx, sy):
            return sx, sy

        motions = [(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (1, -1), (-1, 1), (-1, -1)]
        queue = deque([(sx, sy)])
        visited = {(sx, sy)}

        while queue:
            x, y = queue.popleft()
            for dx, dy in motions:
                nx, ny = x + dx, y + dy
                if not (0 <= nx < static_map.width and 0 <= ny < static_map.height):
                    continue
                if (nx, ny) in visited:
                    continue
                if static_map.is_free_grid(nx, ny):
                    return nx, ny
                visited.add((nx, ny))
                queue.append((nx, ny))

        return None

    def _history_grid_cells(self):
        """Return recent cells visited by this UAV for cross-cycle APF memory."""
        return {
            (int(round(p[0])), int(round(p[1])))
            for p in self.history
        }

    # ==========================================
    # A* global path layer
    # ==========================================
    def plan_global_path(self, static_map, logical_step=0, force=False):
        """
        Generate or refresh the A* global path.

        A* only sees the static inflated grid map. It does not handle moving UAVs.
        Dynamic UAV conflicts are handled later by the local APF layer.
        """
        if self.is_reached:
            return False

        if (not force) and self.global_path and logical_step - self.last_global_replan < self.global_replan_interval:
            self._update_global_path_index()
            return True

        start_grid = self._nearest_free_grid(self._clip_to_grid(self.pos, static_map), static_map)
        goal_grid = self._nearest_free_grid(self._clip_to_grid(self.goal, static_map), static_map)

        if start_grid is None or goal_grid is None:
            self.global_path = []
            self.global_path_index = 0
            return False

        path = astar(start_grid, goal_grid, static_map.grid_map)

        if not path:
            self.global_path = []
            self.global_path_index = 0
            print(f"[A* Warning] UAV {self.id} cannot find a static global path from {start_grid} to {goal_grid}.")
            return False

        self.global_path = path
        self.global_path_index = 0
        self.last_global_replan = logical_step
        self._update_global_path_index()
        return True

    def _update_global_path_index(self):
        """Project current UAV position onto its A* global path and advance the path index."""
        if not self.global_path:
            return

        start_idx = max(0, self.global_path_index - 5)
        candidates = range(start_idx, len(self.global_path))
        nearest_idx = min(
            candidates,
            key=lambda i: math.hypot(self.pos[0] - self.global_path[i][0], self.pos[1] - self.global_path[i][1])
        )

        # Do not move the global index too far backwards; this avoids oscillating on the path.
        self.global_path_index = max(self.global_path_index, nearest_idx)

        # If the current waypoint is already reached, move forward along the global path.
        while self.global_path_index < len(self.global_path) - 1:
            wx, wy = self.global_path[self.global_path_index]
            if math.hypot(self.pos[0] - wx, self.pos[1] - wy) <= 1.0:
                self.global_path_index += 1
            else:
                break

    def _is_far_from_global_path(self, threshold=5.0):
        """Check whether APF has pushed the UAV far away from the current A* path."""
        if not self.global_path:
            return True
        start_idx = max(0, self.global_path_index - 5)
        min_dist = min(
            math.hypot(self.pos[0] - x, self.pos[1] - y)
            for x, y in self.global_path[start_idx:]
        )
        return min_dist > threshold

    def _select_local_target_from_global_path(self):
        """
        Select a short look-ahead waypoint on the A* path as the local APF target.

        APF is no longer attracted directly to the final goal at all times. It tracks
        the A* global path locally, which reduces APF local-minimum problems.
        """
        if not self.global_path:
            self.local_target = self.goal.copy()
            return self.goal.copy()

        self._update_global_path_index()
        target_idx = min(self.global_path_index + self.global_lookahead, len(self.global_path) - 1)
        tx, ty = self.global_path[target_idx]
        self.local_target = np.array([float(tx), float(ty)])
        return self.local_target.copy()

    # ==========================================
    # APF local planning layer
    # ==========================================
    def plan_reference_path(self, static_map, neighbors_info=None, logical_step=0):
        """
        Hybrid planning:
        - A* provides the global route in the static map.
        - Dynamic APF produces the next H local steps toward an A* look-ahead waypoint,
          while considering neighboring UAV repulsion.
        """
        if self.is_reached:
            return

        if self.is_yielding:
            return

        neighbors_info = neighbors_info if neighbors_info else []

        need_global_replan = (
            (not self.global_path) or
            self._is_far_from_global_path(threshold=5.0) or
            (logical_step - self.last_global_replan >= self.global_replan_interval)
        )
        self.plan_global_path(static_map, logical_step=logical_step, force=need_global_replan)

        start_grid = self._clip_to_grid(self.pos, static_map)
        local_target = self._select_local_target_from_global_path()
        local_target_grid = self._clip_to_grid(local_target, static_map)

        full_path = apf(
            start_grid,
            local_target_grid,
            static_map.grid_map,
            dynamic_obstacles=neighbors_info,
            own_safe_radius=self.safe_radius,
            own_id=self.id,
            # Static APF only acts locally around the A* route.
            # A smaller obstacle influence radius prevents over-reacting to far obstacles.
            k_att=1.2,
            k_rep=55.0,
            influence_radius=3.5,
            # Dynamic UAV APF parameters.
            k_dynamic=260.0,
            dynamic_influence_radius=self.comm_range,
            safety_margin=0.5,
            collision_penalty=10000.0,
            swap_penalty=12000.0,
            external_avoid_cells=self._history_grid_cells(),
            external_avoid_penalty=80.0,
            max_iterations=max(static_map.width + static_map.height, self.horizon * 25),
            return_partial=True,
            escape_radius=8,
        )

        planned = self._fill_current_path_from_grid_path(full_path, start_grid)

        # If APF cannot generate a usable local path, fall back to the static A* segment.
        # The conflict-resolution layer will still prevent direct collision.
        if not planned:
            self._fill_current_path_from_global_segment()

    def _fill_current_path_from_grid_path(self, full_path, start_grid=None):
        """Convert an APF grid path into the UAV's rolling-horizon path."""
        self.current_path = []

        if not full_path:
            self.current_path = [self.pos.copy() for _ in range(self.horizon)]
            return False

        if start_grid is not None and len(full_path) > 1 and full_path[0] == start_grid:
            full_path = full_path[1:]

        if not full_path:
            self.current_path = [self.pos.copy() for _ in range(self.horizon)]
            return False

        last_point = np.array([full_path[-1][0], full_path[-1][1]], dtype=float)

        for i in range(self.horizon):
            if i < len(full_path):
                next_pos = np.array([full_path[i][0], full_path[i][1]], dtype=float)
            else:
                next_pos = last_point.copy()
            self.current_path.append(next_pos)

        return True

    def _fill_current_path_from_global_segment(self):
        """Fallback: use the A* path segment when APF cannot produce a local path."""
        self.current_path = []
        if not self.global_path:
            self.current_path = [self.pos.copy() for _ in range(self.horizon)]
            return False

        self._update_global_path_index()
        for i in range(self.horizon):
            idx = min(self.global_path_index + i + 1, len(self.global_path) - 1)
            x, y = self.global_path[idx]
            self.current_path.append(np.array([float(x), float(y)]))
        return True

    def _plan_to_target_with_dynamic_apf(self, target, static_map, neighbors_info):
        """Use dynamic APF to plan a yielding/parking path."""
        start_grid = self._clip_to_grid(self.pos, static_map)
        target_grid = self._clip_to_grid(target, static_map)

        full_path = apf(
            start_grid,
            target_grid,
            static_map.grid_map,
            dynamic_obstacles=neighbors_info if neighbors_info else [],
            own_safe_radius=self.safe_radius,
            own_id=self.id,
            k_att=1.2,
            k_rep=55.0,
            influence_radius=3.5,
            k_dynamic=260.0,
            dynamic_influence_radius=self.comm_range,
            safety_margin=0.5,
            collision_penalty=10000.0,
            swap_penalty=12000.0,
            external_avoid_cells=self._history_grid_cells(),
            external_avoid_penalty=80.0,
            max_iterations=max(static_map.width + static_map.height, self.horizon * 25),
            return_partial=True,
            escape_radius=8,
        )

        return self._fill_current_path_from_grid_path(full_path, start_grid)

    # ==========================================
    # Exchange message with neighbors
    # ==========================================
    def communicate(self, all_uavs):
        neighbors_info = []
        for other in all_uavs:
            if other.id != self.id and self.get_distance(other.pos) <= self.comm_range:
                neighbors_info.append({
                    'id': other.id,
                    'pos': other.pos.copy(),
                    'path': [p.copy() for p in other.current_path],
                    'safe_radius': other.safe_radius,
                })
        return neighbors_info

    # ==========================================
    # Conflict detection and safety backup
    # ==========================================
    def resolve_conflicts_and_replan(self, neighbors_info, static_map):
        if self.is_reached or not self.current_path:
            return

        if self.is_yielding:
            self.yield_timer -= 1
            if self.yield_timer <= 0:
                self.is_yielding = False
            return

        conflict_detected = False
        conflict_neighbor = None

        for step, my_next_pos in enumerate(self.current_path):
            for neighbor in neighbors_info:
                if step < len(neighbor['path']):
                    neighbor_next_pos = neighbor['path'][step]
                else:
                    neighbor_next_pos = neighbor['pos'] if not neighbor['path'] else neighbor['path'][-1]

                dist = np.linalg.norm(my_next_pos - neighbor_next_pos)
                safe_dist = self.safe_radius + neighbor['safe_radius'] + 0.5

                if dist < safe_dist:
                    conflict_detected = True
                    conflict_neighbor = neighbor
                    break
            if conflict_detected:
                break

        if conflict_detected:
            # Priority rule: smaller ID has higher priority.
            # The higher-priority UAV keeps its APF path; the lower-priority UAV
            # waits first and then moves to a parking/yielding point.
            # This avoids the previous problem where both sides may hold still.
            if conflict_neighbor is not None and self.id < conflict_neighbor['id']:
                self.wait_steps = 0
                return

            self.wait_steps += 1

            if self.wait_steps > 3:
                parking_spot = self._find_parking_spot(static_map, neighbors_info, conflict_neighbor)

                if parking_spot is not None:
                    self.is_yielding = True
                    self.yield_timer = max(3, self.horizon)
                    self.wait_steps = 0

                    planned = self._plan_to_target_with_dynamic_apf(
                        target=parking_spot,
                        static_map=static_map,
                        neighbors_info=neighbors_info,
                    )

                    if planned:
                        print(f"[Hybrid Yielding] UAV {self.id} planned an APF parking path, yielding to UAV {conflict_neighbor['id']}.")
                    else:
                        self.current_path = [self.pos.copy() for _ in range(self.horizon)]
                        print(f"[Warning] UAV {self.id} found a parking spot but APF could not generate a safe path to it.")
                else:
                    self.current_path = [self.pos.copy() for _ in range(self.horizon)]
                    print(f"[Warning] UAV {self.id} is trapped and cannot yield.")
            else:
                self.current_path = [self.pos.copy() for _ in range(self.horizon)]
        else:
            self.wait_steps = 0

    def _find_parking_spot(self, static_map, neighbors_info, conflict_neighbor):
        forbidden_grids = set()

        for neighbor in neighbors_info:
            forbidden_grids.add((int(round(neighbor['pos'][0])), int(round(neighbor['pos'][1]))))
            for p in neighbor['path']:
                px, py = int(round(p[0])), int(round(p[1]))
                forbidden_grids.add((px, py))
                if neighbor['id'] == conflict_neighbor['id']:
                    for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                        forbidden_grids.add((px + dx, py + dy))

        history_grids = self._history_grid_cells()

        start_grid = self._clip_to_grid(self.pos, static_map)
        queue = [start_grid]
        visited = {start_grid}
        motions = [(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (1, -1), (-1, 1), (-1, -1)]

        candidates = []
        search_count = 0

        while queue and search_count < 180:
            curr = queue.pop(0)
            search_count += 1
            if 0 <= curr[0] < static_map.width and 0 <= curr[1] < static_map.height:
                if curr not in forbidden_grids and static_map.grid_map[curr[1]][curr[0]] == 0:
                    if curr != start_grid:
                        candidates.append(curr)
                        if len(candidates) >= 20:
                            break

            for dx, dy in motions:
                nx, ny = curr[0] + dx, curr[1] + dy
                if 0 <= nx < static_map.width and 0 <= ny < static_map.height:
                    if (nx, ny) not in visited:
                        visited.add((nx, ny))
                        queue.append((nx, ny))

        if not candidates:
            return None

        best_spot = None
        max_score = -float('inf')
        conf_pos = conflict_neighbor['pos']

        for spot in candidates:
            dist_to_conflict = math.hypot(spot[0] - conf_pos[0], spot[1] - conf_pos[1])

            min_dist_to_uavs = float('inf')
            for neighbor in neighbors_info:
                d = math.hypot(spot[0] - neighbor['pos'][0], spot[1] - neighbor['pos'][1])
                min_dist_to_uavs = min(min_dist_to_uavs, d)
            if min_dist_to_uavs == float('inf'):
                min_dist_to_uavs = 0.0

            min_dist_to_obs = float('inf')
            for cx, cy, r in static_map.circles:
                d = math.hypot(spot[0] - cx, spot[1] - cy) - r
                min_dist_to_obs = min(min_dist_to_obs, d)
            for rx, ry, rw, rh in static_map.rectangles:
                dx = max(rx - spot[0], 0, spot[0] - (rx + rw))
                dy = max(ry - spot[1], 0, spot[1] - (ry + rh))
                d = math.hypot(dx, dy)
                min_dist_to_obs = min(min_dist_to_obs, d)
            if min_dist_to_obs == float('inf'):
                min_dist_to_obs = 0.0

            # Edge penalty: do not prefer parking at the map boundary.
            dist_to_edge = min(spot[0], spot[1], static_map.width - 1 - spot[0], static_map.height - 1 - spot[1])
            edge_score = min(dist_to_edge, 6.0)

            history_penalty = 100.0 if spot in history_grids else 0.0

            score = (
                dist_to_conflict * 1.0 +
                min_dist_to_uavs * 1.5 +
                min_dist_to_obs * 2.0 +
                edge_score * 1.0 -
                history_penalty
            )

            if score > max_score:
                max_score = score
                best_spot = spot

        return np.array([float(best_spot[0]), float(best_spot[1])])

    # ==========================================
    # Move one step
    # ==========================================
    def step_forward(self):
        if np.linalg.norm(self.pos - self.goal) < 0.1:
            self.is_reached = True
            return

        if self.current_path:
            self.history.append(self.pos.copy())
            if len(self.history) > 12:
                self.history.pop(0)

            next_step = self.current_path.pop(0)

            # Safety clip: one logical step should not exceed max_speed.
            delta = next_step - self.pos
            dist = np.linalg.norm(delta)
            if dist > self.max_speed and dist > 1e-9:
                next_step = self.pos + delta / dist * self.max_speed

            self.velocity = next_step - self.pos
            self.pos = next_step
            self.trajectory.append(self.pos.copy())

            if np.linalg.norm(self.pos - self.goal) < 0.1:
                self.is_reached = True


# ==========================================
# Main simulation
# ==========================================
def run_simulation(
    width=50,
    height=50,
    num_obstacles=50,
    map_seed=42,
    inflation_radius=0.8,
    max_logical_steps=500,
    render_frames_per_step=5,
):
    """Run the hybrid A* + dynamic APF multi-UAV planning simulation."""
    test_circles, test_rectangles, density = generate_test_map(
        width=width,
        height=height,
        num_obstacles=num_obstacles,
        seed=map_seed,
    )

    print("Map generated successfully.")
    print(f"  width={width}, height={height}")
    print(f"  obstacles={num_obstacles}, density={density:.2%}, seed={map_seed}")
    print(f"  circles={len(test_circles)}, rectangles={len(test_rectangles)}")

    env_map = StaticMap(
        width,
        height,
        circles=test_circles,
        rectangles=test_rectangles,
        inflation_radius=inflation_radius,
    )

    uav_tasks = [
        ([2, 4], [width - 2, height - 4]),
        ([4, 2], [width-4, height - 2]),
        ([2, height - 4], [width - 2, 4]),
        ([4, height - 2], [width-4, 2]),

        ([width-2, 4], [2, height - 4]),
        ([width-4, 2], [4, height - 2]),
        ([width - 2, height-4], [2, 4]),
        ([width - 4, height-2], [4, 2]),
    ]

    uavs = [
        UAV(
            uav_id=i,
            start=start,
            goal=goal,
            safe_radius=0.8,
            comm_range=7.0,
            horizon=5,
            global_lookahead=8,
        )
        for i, (start, goal) in enumerate(uav_tasks, start=1)
    ]

    # Initial static global planning.
    for uav in uavs:
        uav.plan_global_path(env_map, logical_step=0, force=True)

    do_render = render_frames_per_step > 0
    if do_render:
        plt.ion()
        fig, ax = plt.subplots(figsize=(8, 8))
        cmap = plt.get_cmap("tab20")
    else:
        fig = ax = None

    for t in range(max_logical_steps):
        # 1) Communication first. APF needs neighbor future paths for dynamic repulsion.
        neighbor_infos = {uav.id: uav.communicate(uavs) for uav in uavs}

        # 2) A* global waypoint tracking + local APF conflict handling.
        for uav in uavs:
            uav.plan_reference_path(env_map, neighbor_infos[uav.id], logical_step=t)

        # 3) Keep conflict detection / yielding as a backup safety layer.
        for uav in uavs:
            neighbors_info = uav.communicate(uavs)
            uav.resolve_conflicts_and_replan(neighbors_info, env_map)

        old_positions = {uav.id: uav.pos.copy() for uav in uavs}
        for uav in uavs:
            uav.step_forward()

        if do_render:
            for f in range(render_frames_per_step):
                ax.clear()

                for rx, ry, rw, rh in env_map.rectangles:
                    ax.add_patch(
                        patches.Rectangle(
                            (rx, ry), rw, rh,
                            linewidth=1,
                            edgecolor='black',
                            facecolor='gray',
                            alpha=0.5,
                        )
                    )
                for cx, cy, r in env_map.circles:
                    ax.add_patch(plt.Circle((cx, cy), r, color='gray', alpha=0.5))

                alpha = (f + 1) / render_frames_per_step

                for uav in uavs:
                    color = cmap((uav.id - 1) % 20)
                    interp_pos = old_positions[uav.id] * (1 - alpha) + uav.pos * alpha

                    # A* global path, shown as a dotted line.
                    if uav.global_path:
                        gx = [p[0] for p in uav.global_path]
                        gy = [p[1] for p in uav.global_path]
                        ax.plot(gx, gy, ':', color=color, alpha=0.25, linewidth=1)

                    # Executed trajectory.
                    if len(uav.trajectory) > 1:
                        hx = [p[0] for p in uav.trajectory]
                        hy = [p[1] for p in uav.trajectory]
                        ax.plot(hx, hy, '-', color=color, alpha=0.35, linewidth=1)

                    # APF rolling-horizon local trajectory.
                    if uav.current_path:
                        path_x = [interp_pos[0]] + [p[0] for p in uav.current_path]
                        path_y = [interp_pos[1]] + [p[1] for p in uav.current_path]
                        ax.plot(path_x, path_y, '--', color=color, alpha=0.65, linewidth=1.5)

                    # Local target selected from A* path.
                    ax.plot(uav.local_target[0], uav.local_target[1], 's', color=color, markersize=4, alpha=0.7)

                    # UAV and final goal.
                    ax.plot(interp_pos[0], interp_pos[1], 'o', color=color, markersize=5)
                    ax.add_patch(plt.Circle((interp_pos[0], interp_pos[1]), uav.safe_radius, color=color, alpha=0.15))
                    ax.plot(uav.goal[0], uav.goal[1], 'x', color=color, markersize=10, linewidth=2)
                    ax.text(interp_pos[0] + 0.5, interp_pos[1] + 0.5, f'UAV{uav.id}', fontsize=9)

                ax.set_xlim(0, env_map.width)
                ax.set_ylim(0, env_map.height)
                ax.set_aspect('equal')
                ax.set_title(f"Hybrid A* Global + APF Local - Logic Step {t} | Render Frame {f + 1}/{render_frames_per_step}")
                ax.grid(True)

                plt.pause(0.01)

        if all(uav.is_reached for uav in uavs):
            print(f"所有无人机已在第 {t} 步到达终点！")
            break
    else:
        print(f"仿真结束：达到最大逻辑步数 {max_logical_steps}。")
        for uav in uavs:
            print(f"  UAV{uav.id}: pos={uav.pos}, goal={uav.goal}, reached={uav.is_reached}")

    if do_render:
        plt.ioff()
        plt.show()

    return uavs, env_map


if __name__ == "__main__":
    run_simulation(
        width=50,
        height=50,
        num_obstacles=50,
        map_seed=42,       # use None for a different random map each run
        inflation_radius=0.8,
        max_logical_steps=500,
        render_frames_per_step=5,
    )
